### ISSUE TITLE
Feature 1:  List Books

### ISSUE THREAD

**Issue by csys-fresher-batch-2021** [csys-fresher-batch-2021/bookshopapp-rathika#14]
#### User Story

* As a user, I should be able to view books.

**Comment by csys-fresher-batch-2021** [comment]
![image](https://user-images.githubusercontent.com/83430615/120861877-9bda9000-c5a5-11eb-81d6-80a87094de93.png)

**Comment by csys-fresher-batch-2021** [comment]
#### Code
![image](https://user-images.githubusercontent.com/83430615/120862588-d7298e80-c5a6-11eb-948e-19ac444f9c8d.png)

**Comment by Rathika12** [comment]
Fixed the issue.
