### ISSUE TITLE
Feature 2: Search Books by language

### ISSUE THREAD

**Issue by csys-fresher-batch-2021** [csys-fresher-batch-2021/bookshopapp-rathika#15]
#### User Story:
* As a user, I should be able to search books by language.

**Comment by csys-fresher-batch-2021** [comment]
#### Code
![image](https://user-images.githubusercontent.com/83430615/120862820-338cae00-c5a7-11eb-834e-4385921d461a.png)
![image](https://user-images.githubusercontent.com/83430615/120862851-3e474300-c5a7-11eb-9d06-bc7d88b8bb4a.png)

**Comment by csys-fresher-batch-2021** [comment]
![image](https://user-images.githubusercontent.com/83430615/120863687-9599e300-c5a8-11eb-9ac1-ddf4c18e5dd4.png)

**Comment by Rathika12** [comment]
Fixed the bug and merged
